### ISSUE TITLE
Not fully installed

### ISSUE THREAD

**Issue by Macadoshis** [baloise/dashboard-plus#10]
I can't get it fully installed on my standalone self-hosted Atlassian Bitbucket Server.

![image](https://cloud.githubusercontent.com/assets/2878861/16199822/639de8aa-370b-11e6-9aa7-a7e688af6212.png)

Why are the first 3 modules deactivated ? Are there prerequisites plugins I need to install first ?

**Comment by greg-junkietech** [comment]
[Dashboard+](https://marketplace.atlassian.com/plugins/com.baloise.confluence.dashboard-plus/server/overview) is a **Confluence** Plugin that provides all 3 Confluence macros, that your **Bitbucket Server** was not able to activate. So far ok.
Or what did you expect there exactly?

**Comment by greg-junkietech** [comment]
No news good news, closing this issue
