### ISSUE TITLE
Compatibility update for Confluence version 6.2.2 / 6.11.0 / 6.12.2

### ISSUE THREAD

**Issue by culmat** [baloise/dashboard-plus#12]

**Comment by culmat** [comment]
Hi Greg,
can we update to com.offbytwo.jenkins:jenkins-client:0.3.7 ?
When I run on my machine I get ClassNotFound exceptions. 
I would like to remove the patched offbytwo-classes from the source code.
Regards
Matthias

**Comment by greg-junkietech** [comment]
Hi Matthias,
ClassNotFoundException means to me you have a setup problem with the project.
I wouldnt try to remove a patched class, it had been overloaded for some reasons in the past. If I remember well, a new method had been introduced in a jenkins-client class.
Can you focus on fixing the project setup first?
Bye & cheers, Greg

**Comment by MarkusTiede** [comment]
@culmat and @greg-junkietech could you please take a look at branch "issue-12_experimentalUpgradeTo037"

I've update all of the patched sources that have been modified and did the modifications again.

Now at least it's compiling (@culmat : I wasn't able to compile it either until doing these modifications).

However the modifications are imho quite significant; it's not only a newly introduced method.

**Comment by MarkusTiede** [comment]
I assume this aligns with

![image](https://user-images.githubusercontent.com/1764012/45229504-41ae2280-b2c6-11e8-85a8-d627827255af.png)

**Comment by MarkusTiede** [comment]
Another request came in to support 6.12.0.

@greg-junkietech : can you tell whether we can provide such an update in the next couple of weeks?

**Comment by greg-junkietech** [comment]
See 3 new compatibility updates for Confluence 6.2.3, Confluence 6.12.0 and Confluence 6.13.0 on [ATLASSIAN Marketplace](https://marketplace.atlassian.com/apps/1212499/dashboard/version-history)
