### ISSUE TITLE
Add support for addressing Jenkins Jobs via their "Full project name" when using the Cloudbees Folder Plugins

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/dashboard-plus#13]
Please add support for addressing Jenkins jobs via their "Full project name"; e.g. when using the [Folder Plugins](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin) a job name might no longer be unique (enough) to perform the lookup.

```
parent/folder/structure/SomeJobsName
```

Currently it results in "No Job 'parent/folder/structure/SomeJobsName' found on Jenkins.

**Comment by greg-junkietech** [comment]
The Jenkins Job Status macro does actually support such Jenkins jobs nested in folders when using the Cloudbees Folder Plugins.

You just need to **translate each folder level with an additional `/job` as part of the Job name**.
In your example with a job called `SomeJobsName` located in the 3rd level folder `parent/folder/structure`, you need to pass ```parent/job/folder/job/structure/job/SomeJobsName``` as macro parameter `Job name`.

OK for you?

**Comment by MarkusTiede** [comment]
Agreeing - ok for now though its using more (dependent) information than really necessary.
