### ISSUE TITLE
I have managed to set this up and the icon shows on my page but with a ? and it has no colour, please can you tell me what I'm doing wrong?

### ISSUE THREAD

**Issue by paulacope** [baloise/dashboard-plus#3]
Problems with setup

**Comment by culmat** [comment]
Hi Paula,
have you tried hovering over the '?'. When I enter an invalid URL (i.a. behind a proxy) I get the following: 
![2015-06-22 08_30_08-dashboard plus - demonstration space - confluence](https://cloud.githubusercontent.com/assets/638519/8276620/fab209be-18b8-11e5-9943-e45597cc9627.png)

**Comment by greg-junkietech** [comment]
Hi Paula,
Can I close this issue now?
Please give feedback wether the problem is fixed at your end, thanks.

**Comment by paulacope** [comment]
HI,

I never got it fixed for the Sonar reports.

Thanks

Paula

**Comment by greg-junkietech** [comment]
How does the rendered widget looked like, do you get more details in the tooltip appearing when you mouse hover over the widget?

**Comment by greg-junkietech** [comment]
Hi Paula,
Can you please inform if you are still facing the issue or if you could solve it?
Many thanks, regards.

**Comment by greg-junkietech** [comment]
Having no recent feedback, OK for you if I now close this issue?

**Comment by paulacope** [comment]
OK thanks
