### ISSUE TITLE
Not able to get status

### ISSUE THREAD

**Issue by rraviprakash** [baloise/dashboard-plus#6]
Hi,

i used fully qualified name, verified all the issues reported in previous issue tickets and still not getting status. on mouse over getting ${testDetails} . Do we need any plugin in jenkins for it to work? Thanks.

Jenkins ver. 1.551
Atlassian Confluence 5.7

**Comment by greg-junkietech** [comment]
Hi,

What version of the plugin are you using?
Can you provide the confluence logs?

Br, Greg

**Comment by rraviprakash** [comment]
HI Greg,

we are using 1.2.2 version of the plugin. Status is showing fine from other instances of jenkins used by different development team.

**Comment by greg-junkietech** [comment]
If you say the plugin works on one confluence installation for different jenkins instances and you have (only) trouble using a particular jenkins instance, the problem is probably related to that jenkins instance. Or to the macro parameters you defined for your status light.
Can you provide screenshots showing your macro parameters and the rendered widget incl. mouse hover tooltip?

**Comment by rraviprakash** [comment]
Greg,

We are showing the status from different jenkins, The status is visible from couple of jenkins and failing for an instance of jenkins.


The first row is the one which is not showing result.

Confluence Dashboard:
[cid:image001.png@01D11590.0C64C6A0]

Not Working:

[cid:image002.png@01D11590.0C64C6A0]


Regards
Raviprakash Ramamoorthy
_________________________________________________
+91 80 4031 8397 (Desk) | +91 7829 334 555 (Mobile)

**Comment by greg-junkietech** [comment]
Unfortunately I cannot see your attachments, can you please re-upload them?
Using drag & drop, they should appear with the following syntax in your comment text:
`![Alt Text](url)`

**Comment by greg-junkietech** [comment]
It is maybe worth to be mentioned, I have meant above the handling of attachments in your comment via [GitHub Issues form](https://github.com/baloise/dashboard-plus/issues)

**Comment by rraviprakash** [comment]
The upload is failing. Please let me know if there is any alternate way to share the screen shot. Thanks.

**Comment by greg-junkietech** [comment]
Simply by email @ greg.junkietech@gmail.com

**Comment by rraviprakash** [comment]
PFA.


Regards
Raviprakash Ramamoorthy
_________________________________________________
+91 80 4031 8397 (Desk) | +91 7829 334 555 (Mobile)

**Comment by rraviprakash** [comment]
emailed you the attachments.

**Comment by greg-junkietech** [comment]
OK, you probably have a network connectivity issue, means your confluence server couldnt reach the targeted jenkins instance.
Please check (or ask your confluence admin) whether requesting the URL `http://ld01.eur.ad.tullib.com:8090/jenkins/job/DMS-DEV-BUILD-DEPLOY/api/json` succeeds or not (maybe a proxy configuration is missing there).
BTW: the latest plugin version 1.2.9 has enhanced exception handling and would render a comprehensive error in that case.
Does this help you?

**Comment by rraviprakash** [comment]
We are able to access the URL from confluence server.

**Comment by rraviprakash** [comment]
After upgrade status not working from all our jenkins instance. Sent you the error screenshot.

**Comment by greg-junkietech** [comment]
This problem has been already addressed, see issue #5, not yet resolved:
the current solution is to try with this [special plugin version](https://github.com/baloise/dashboard-plus/releases/download/atlassian_mp%2F1.2.9-no-commons-logging/dashboard-plus-1.2.9-no-commons-logging.jar), that contains no commons-logging classes.

Can you please try and give feedback? Thanks!

**Comment by rraviprakash** [comment]
After installing the special plugin version, we are able to identify the issue. The plugin is truncating part of port. i.e., we have hosted jenkins in port 8090 and plugin is trying to reach jenkins on port 80. Also  observed it works fine on port 8080 and 9000.

we have updated the port to make it work now. Thanks for your support in identifying the issue.

**Comment by greg-junkietech** [comment]
Having checked the plugin again, I see technically no reason why the plugin would truncate a part of the port in the host URL, and how it would transform this
`http://www.myhost.com:8090/some-jenkins-context/job/my-job`
into this
`http://www.myhost.com:80/some-jenkins-context/job/my-job`
or this
`http://www.myhost.com/some-jenkins-context/job/my-job`
This behaviour may be related to a reverse proxy on the jenkins server: you can check this by invoking from your confluence server the jenkins REST API like the plugin does and ensure that following URL returns JSON formatted content:
'wget http://www.myhost.com/some-jenkins-context/job/my-job/api/json'

**Comment by rraviprakash** [comment]
We are able to get json formatted content on accessing the URL from confluence server. Since the plugin in not doing this, i will check our server settings. The issue can be closed now. Thanks for your support.

**Comment by greg-junkietech** [comment]
Can you keep updated about your findings, it may be useful for other users, thanks.
I wait before closing the issue.

**Comment by rraviprakash** [comment]
Greg,

It's our setup issue. Jenkins base URL was configured with port 80 in configuration section and hence we were getting that issue.
